// Generated by graphql-go-gen
// DO NOT EDIT THIS FILE MANUALLY

import { TypedDocumentNode } from '@graphql-typed-document-node/core';
import { print } from 'graphql';
import gql from 'graphql-tag';

