// Generated by graphql-go-gen - TypedDocumentNode Plugin
// DO NOT EDIT THIS FILE MANUALLY

import gql from 'graphql-tag';
import { TypedDocumentNode } from '@graphql-typed-document-node/core';

// Operation definitions
export const GetUserProfileDocument = gql`
query GetUserProfile($userId: ID!) {
	user(id: $userId) {
		id
		username
		email
		profile {
			bio
			avatarUrl
			location
		}
		posts {
			id
			title
			status
			createdAt
		}
	}
}

` as unknown as TypedDocumentNode<GetUserProfileQuery, GetUserProfileQueryVariables>;

export const UpdateUserBioDocument = gql`
mutation UpdateUserBio($userId: ID!, $bio: String!) {
	updateUser(id: $userId, input: {profile:{bio:$bio}}) {
		id
		profile {
			bio
		}
	}
}

` as unknown as TypedDocumentNode<UpdateUserBioMutation, UpdateUserBioMutationVariables>;

