// Generated by graphql-go-gen
// DO NOT EDIT THIS FILE MANUALLY

// Scalar type mappings
export type DateTime = string;
export type UUID = string;

// Enum types
export type PostStatus =
  | 'DRAFT'
  | 'PUBLISHED'
  | 'ARCHIVED';


// Input types
export interface CreatePostInput {
  title: string;
  content: string;
  authorId: string;
  tags: string[] | null | null;
  status: PostStatus | null;
}

export interface CreateUserInput {
  username: string;
  email: string;
  profile: UserProfileInput | null;
}

export interface UpdateUserInput {
  username: string | null;
  email: string | null;
  profile: UserProfileInput | null;
}

export interface UserProfileInput {
  bio: string | null;
  avatarUrl: string | null;
  location: string | null;
}


// Object types
export interface Mutation {
  __typename?: 'Mutation';
  createUser: User;
  updateUser: User;
  createPost: Post;
}

export interface Post {
  __typename?: 'Post';
  id: string;
  title: string;
  content: string;
  author: User;
  tags: string[];
  status: PostStatus;
  createdAt: string;
  updatedAt: string;
}

export interface Query {
  __typename?: 'Query';
  user: User | null;
  users: User[];
  posts: Post[];
  __schema: __Schema;
  __type: __Type | null;
}

export interface User {
  __typename?: 'User';
  id: string;
  username: string;
  email: string;
  profile: UserProfile | null;
  posts: Post[];
  createdAt: string;
  updatedAt: string;
}

export interface UserProfile {
  __typename?: 'UserProfile';
  bio: string | null;
  avatarUrl: string | null;
  location: string | null;
}


// Interface types

// Union types

