// Generated by graphql-go-gen
// DO NOT EDIT THIS FILE MANUALLY

// Scalar type mappings
export type Date = string;
export type DateTime = string;
export type JSON = any;
export type Time = string;
export type UUID = string;

// Enum types
export type __DirectiveLocation =
  | 'PLACEHOLDER';

export type __TypeKind =
  | 'PLACEHOLDER';


// Input types

// Object types
export interface Query {
  __typename?: 'Query';
  // TODO: Add object fields
}


// Interface types

// Union types

// Operation types
export interface CreatePostVariables {
  input: CreatePostInput;
}

export interface CreatePostResult {
  // TODO: Add result fields based on selection set
}

export interface CreateUserVariables {
  input: CreateUserInput;
}

export interface CreateUserResult {
  // TODO: Add result fields based on selection set
}

export interface GetUserVariables {
  id: string;
}

export interface GetUserResult {
  // TODO: Add result fields based on selection set
}

export interface ListUsersVariables {
  limit: number | null;
  offset: number | null;
}

export interface ListUsersResult {
  // TODO: Add result fields based on selection set
}

